### ISSUE TITLE
"how does Cucumber decide which scenarios to run?"

### ISSUE THREAD

**Issue by ryanwmarsh** [cucumber-ltd/shouty.java#13]
In the workbook we currently ask... 
"how does Cucumber decide which scenarios to run?"
This is not easily understood by the student. 

Would it not be more modern and more clear to use the options annotation and be explicit about the path for the benefit of the student? 
```java
@CucumberOptions (features = "src/test/resources/shouty/")
```

**Comment by aslakhellesoy** [comment]
Moved to cucumber-ltd/workbooks#4

**Comment by aslakhellesoy** [comment]
The answer to the workbook question is: It runs all feature files found underneath directories on the classpath. Maven puts `src/test/resources` on the classpath.

We could make it explicit as you suggest, but I think it's just as important that students understand what Cucumber's default behaviour is. By making it explicit with an annotation, wouldn't that obscure the understanding of default behaviour? Not sure...
